# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{seo_checker}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Huang"]
  s.date = %q{2010-03-06}
  s.description = %q{seo_checker check your website if it is seo.}
  s.email = %q{flyerhzm@gmail.com}
  s.executables = ["seo_checker", "seo_checker"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "bin/seo_checker",
     "lib/seo_checker.rb",
     "seo_checker.gemspec"
  ]
  s.homepage = %q{http://github.com/flyerhzm/seo_checker}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{seo_checker check your website if it is seo.}
  s.test_files = [
    "examples/bad_seo/config/routes.rb",
     "examples/bad_seo/config/initializers/backtrace_silencers.rb",
     "examples/bad_seo/config/initializers/new_rails_defaults.rb",
     "examples/bad_seo/config/initializers/session_store.rb",
     "examples/bad_seo/config/initializers/inflections.rb",
     "examples/bad_seo/config/initializers/mime_types.rb",
     "examples/bad_seo/config/environment.rb",
     "examples/bad_seo/config/boot.rb",
     "examples/bad_seo/config/environments/production.rb",
     "examples/bad_seo/config/environments/development.rb",
     "examples/bad_seo/test/test_helper.rb",
     "examples/bad_seo/test/performance/browsing_test.rb",
     "examples/bad_seo/test/functional/posts_controller_test.rb",
     "examples/bad_seo/test/unit/helpers/posts_helper_test.rb",
     "examples/bad_seo/test/unit/post_test.rb",
     "examples/bad_seo/db/migrate/20100228140057_create_posts.rb",
     "examples/bad_seo/db/seeds.rb",
     "examples/bad_seo/db/schema.rb",
     "examples/bad_seo/app/helpers/application_helper.rb",
     "examples/bad_seo/app/helpers/posts_helper.rb",
     "examples/bad_seo/app/models/post.rb",
     "examples/bad_seo/app/controllers/application_controller.rb",
     "examples/bad_seo/app/controllers/posts_controller.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

